### ISSUE TITLE
CollectionProxy optimization has side effects

### ISSUE THREAD

**Issue by tjchambers** [aktsk/octoball#1]
There was an optimization added in 0.1.3 that purports to optimize the create under the CollectionProxy logic. 

We are using Octoball to replace Octopus and in our CI testing we noted a difference in results under the condition like:

`ModelX.where(region_id: regions)`

when regions is a CollectionProxy. The resulting SQL under Octoball 0.1.3 was

`select * from model_x where model_x.region_id = NULL` 

We traced this to https://github.com/aktsk/octoball/blob/c759128f0fa2b47a40915bd6805f251cd5f50f6d/lib/octoball/association.rb#L29

By commenting https://github.com/aktsk/octoball/blob/c759128f0fa2b47a40915bd6805f251cd5f50f6d/lib/octoball/association.rb#L76

the SQL that was generated was correctly embeding the SQL snippet for `regions` in place of the `NULL`.  My inference is that this optimization has negative side effects.

**Comment by patodevilla** [comment]
Awesome job with this gem!

Is there a workaround for this issue? I am migrating my app from Octopus to Rails 6.

By the way, has anyone used this app in a production environment? would appreciate any experience. I'll post mine as soon as I have it up and running.

**Comment by sekiyama58** [comment]
Hi @tjchambers, thank you for reporting this issue!
I believe #2 will fix the it.

**Comment by sekiyama58** [comment]
Since this issue is addressed  in octoball-0.1.4 release, I'm going to close this issue.
Please reopen this if you still have a problem.
