### ISSUE TITLE
Is it possible to change an ActiveRecord object's shard on the fly

### ISSUE THREAD

**Issue by nebel95** [aktsk/octoball#3]
First of all, thank you for your work with this gem! It is a great help!

My rails app connects to 2 databases: `master` and `replica`. `replica` is a read-only replica of `master`, i.e. any write to `master` will also be done `replica` but no one can directly write something in `replica`. With `octopus`, I can do something like below:

```ruby
# Read from replica to reduce workload on master, most of the database connections on master is used for write operations
user = User.using(:replica).find_by_id(123)

if some_condition
  user.name = "Changed Name"

  # switch to master to perform a save
  user.current_shard = :master
  user.save
end
```

Is it possible to do something similar with `octoball`? Thanks in advance!

**Comment by sekiyama58** [comment]
So far, Octoball doesn't have the setter method for current_shard.

```ruby
user.instance_variable_set(:@current_shard, :master)
```
or
```ruby
# somewhere in config/initializers/*.rb
ActiveRecord::Base.class_eval { attr_writer :current_shard }
# and then
user.current_shard = :master
```
can do the same thing. 

However, I'm not sure if this is a common use case, as transaction security can be compromised without special care.

**Comment by nebel95** [comment]
Thank you! That works for me for now.
