### ISSUE TITLE
Is this gem tested/compatible with rails 7?

### ISSUE THREAD

**Issue by patodevilla** [aktsk/octoball#6]
First of all... AWESOME GEM! It saved my life when migrating from octopus.

Just wanted to know if it is compatible with rails 7.

**Comment by yasuno0327** [comment]
Hi patodevilla,

Thank you for the kind words! 
To answer your question, I have personally used this gem with Rails 7 and did not encounter any issues. 
While we haven't officially tested it yet, there shouldn't be any problems as long as everything is working normally.
We plan to add Rails 7 compatibility tests in the near future.

If you encounter any issues with this gem while using Rails 7, please feel free to open an issue and we'll do our best to address it. 

Thank you!

**Comment by sekiyama58** [comment]
At least, it passes the rspec test with ActiveRecord 7: https://github.com/aktsk/octoball/actions/runs/4729279164/jobs/8391629451#step:4:52
(if the link above doesn't show the actual line, please see the `Setup Ruby` step then you can see `Using activerecord 7.0.4.3` )

**Comment by patodevilla** [comment]
Awesome!!! 🚀
